name: Build and deploy ASP.Net Core app to Azure Web App - pinpoint2055

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release ./api/api.sln  # Specify the solution file path

      - name: dotnet publish
        run: dotnet publish --configuration Release --output "${{env.DOTNET_ROOT}}/myapp" ./api/api.sln  # Specify the solution file path

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_505EB1CA6BC946848CF34D489C965B5F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_00C05BE7D1734CFBA6F83F2C35695B34 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_84CB855D034F4393A7685F09101683DA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pinpoint2055'
          slot-name: 'Production'
          package: ${{ env.DOTNET_ROOT }}/myapp # Ensure this points to the correct path
